services:
  redis:
    image: "redis:latest"
    container_name: redis
    command: "redis-server --appendonly yes --requirepass password"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"

  ntopng:
    image: "ntop/ntopng_arm64.dev:latest"
    container_name: ntopng
    command: "--community -d -w 9898 -W 0 -i eth0 --redis 127.0.0.1:6379:password"
    network_mode: host
    restart: always
    environment:
      TZ: "Asia/Bangkok"
    volumes:
      - "./ntopng-dist:/usr/share/ntopng/httpdocs/dist"
    depends_on:
      - redis
